# Generated by Django 4.2.2 on 2023-07-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="copies_count",
            field=models.IntegerField(default=1),
        ),
    ]
