# Generated by Django 4.2.2 on 2023-07-05 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="copies_count",
        ),
    ]
