# Generated by Django 4.2.2 on 2023-07-04 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_copies_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["id"]},
        ),
    ]
