# Generated by Django 4.2.2 on 2023-07-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loans",
            name="blocking_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="loans",
            name="loan_return",
            field=models.DateTimeField(null=True),
        ),
    ]
