# Generated by Django 4.2.2 on 2023-07-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0001_initial"),
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loans",
            name="copy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loans",
                to="copies.copy",
            ),
        ),
    ]
