# Generated by Django 4.2.2 on 2023-07-09 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loans",
            name="blocking_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="loans",
            name="loan_initial",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="loans",
            name="loan_return",
            field=models.DateField(null=True),
        ),
    ]
