# Generated by Django 4.2.2 on 2023-07-03 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_alter_loans_copy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loans",
            name="loan_return",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2023, 7, 10, 20, 9, 56, 711001, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
