# Generated by Django 4.2.2 on 2023-07-09 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_alter_loans_blocking_date_alter_loans_loan_initial_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loans",
            name="blocking_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="loans",
            name="loan_initial",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="loans",
            name="loan_return",
            field=models.DateTimeField(null=True),
        ),
    ]
