# Generated by Django 4.2.2 on 2023-07-03 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0004_alter_loans_loan_return"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loans",
            name="loan_return",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2023, 7, 10, 20, 11, 50, 319152, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
