# Generated by Django 4.2.2 on 2023-07-05 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0008_alter_loans_loan_return"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loans",
            name="loan_return",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2023, 7, 12, 16, 29, 14, 163532, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
