# Generated by Django 4.2.2 on 2023-08-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Copy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_stock", models.BooleanField(default=True, null=True)),
                ("copies_count", models.PositiveIntegerField(null=True)),
                ("is_available", models.BooleanField(default=True, null=True)),
                ("serial_number", models.CharField(max_length=600, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="books.book",
                    ),
                ),
            ],
        ),
    ]
