# Generated by Django 4.2.2 on 2023-07-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copy",
            name="copies_count",
            field=models.CharField(null=True),
        ),
    ]
