# Generated by Django 4.2.2 on 2023-07-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_alter_copy_copies_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copy",
            name="copies_count",
            field=models.IntegerField(null=True),
        ),
    ]
