# Generated by Django 4.2.2 on 2023-07-04 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_copy_copies_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="copy",
            options={"ordering": ["id"]},
        ),
    ]
