# Generated by Django 4.2.3 on 2023-07-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_copy_copies_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="in_stock",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
