# Generated by Django 4.2.2 on 2023-07-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0003_alter_copy_copies_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="copy",
            old_name="in_stock",
            new_name="is_available",
        ),
        migrations.RemoveField(
            model_name="copy",
            name="copies_count",
        ),
        migrations.AddField(
            model_name="copy",
            name="serial_number",
            field=models.CharField(null=True),
        ),
    ]
